name: Build
"on":
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      # v4.4.0
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      - name: Install uv
        # v3.2.4
        uses: astral-sh/setup-uv@caf0cab7a618c569241d31dcd442f54681755d39
      - name: Set up Python
        run: uv python install 3.13
      - name: Check lockfile is up to date
        run: uv lock --check
      - name: Build package
        run: uv build
      - name: Check package metadata
        run: uv tool run twine check dist/*
      - name: Upload artifacts
        # v4.6.2
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: dist
          path: dist/
